# tmux config
set-option -g default-terminal "screen-256color"
set -ga terminal-overrides ",screen-256color*:Tc"

set -s escape-time 0

set-option -g history-limit 5000
set -g base-index 1

set -g focus-events

# left bar
set-option -g status-style bg=default
set -g status-position bottom
set -g status-right '%H:%M:%S %d/%m/%Y'
set -g status-right-length 50
set -g status-left-length 20

# selection color
set -g mode-style "fg=default,bg=#393b44"
